# GitHub Actions Quality Workflow
# Disabled by default - enable by setting repository variable ENABLE_CLAUDE_CI=true

name: Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger also available

jobs:
  lint:
    if: ${{ vars.ENABLE_CLAUDE_CI == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint

  test:
    if: ${{ vars.ENABLE_CLAUDE_CI == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm test
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: always()

  e2e:
    if: ${{ vars.ENABLE_CLAUDE_CI == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright
        run: npx playwright install --with-deps
      
      - name: Run E2E tests
        run: npm run test:e2e
      
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/

  build:
    if: ${{ vars.ENABLE_CLAUDE_CI == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Check build size
        run: |
          if [ -d ".next" ]; then
            du -sh .next
          fi

# Enable this workflow by:
# 1. Set repository variable: ENABLE_CLAUDE_CI=true in GitHub Settings > Secrets and variables > Actions > Variables
# 2. Or set ci.enabled: true in .claude/config.yaml (will add ENABLE_CLAUDE_CI automatically when pushing)
# 3. Or tell the orchestrator: "Enable CI workflows"
